"""empty message

Revision ID: 33abb933ac0f
Revises: a2ed7b0165ae
Create Date: 2024-09-18 22:19:28.901964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33abb933ac0f'
down_revision = 'a2ed7b0165ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blacklists',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('acc_key', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('bid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Blacklists')
    # ### end Alembic commands ###
