"""empty message

Revision ID: a2ed7b0165ae
Revises: 13d07196fb0e
Create Date: 2024-09-16 10:32:34.846866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ed7b0165ae'
down_revision = '13d07196fb0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallary', sa.String(), nullable=True))
        batch_op.drop_column('video')
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('video', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('gallary')

    # ### end Alembic commands ###
