"""empty message

Revision ID: 13d07196fb0e
Revises: 1013f86a39ce
Create Date: 2024-09-15 00:13:44.623851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d07196fb0e'
down_revision = '1013f86a39ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video', sa.String(), nullable=True))
        batch_op.drop_column('content_')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('video')
        batch_op.drop_column('picture')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
